# Generated by Django 5.0.4 on 2024-05-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='desctiption',
            new_name='description',
        ),
    ]
