# Generated by Django 5.0.6 on 2024-06-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0001_initial'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(to='people_app.people'),
        ),
        migrations.DeleteModel(
            name='Management',
        ),
    ]
