# Generated by Django 5.0.6 on 2024-05-22 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subcategory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=800)),
                ('institutional_email', models.EmailField(max_length=100)),
                ('personal_page_link', models.URLField()),
                ('category', models.CharField(choices=[('institution', 'Institution'), ('physical person', 'Physical person')], max_length=20)),
                ('subcategory_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory_app.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
                ('people_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_app.people')),
            ],
        ),
    ]
