# Generated by Django 5.0.6 on 2024-05-25 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0002_alter_people_options_rename_senha_login_password_and_more'),
        ('subcategory_app', '0002_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='logo',
            field=models.ImageField(blank=True, upload_to='people_logos/'),
        ),
        migrations.AddField(
            model_name='people',
            name='subcategory_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subcategory_app.subcategory'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='institutional_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='personal_page_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
