# Generated by Django 5.0.6 on 2024-05-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0004_alter_people_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
