# Generated by Django 5.0.6 on 2024-06-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0005_alter_people_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
