# Generated by Django 5.0.6 on 2024-06-06 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0006_delete_login'),
        ('subcategory_app', '0002_alter_subcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='subcategory_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subcategory_app.subcategory'),
        ),
    ]
