# Generated by Django 5.0.6 on 2024-05-18 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(unique=True)),
                ('category', models.CharField(choices=[('LC', 'Lecture'), ('FR', 'Fair'), ('CF', 'Conference'), ('WK', 'Workshop'), ('SM', 'Seminary'), ('AE', 'Art Exhibition'), ('FV', 'Festival'), ('OT', 'Others')], default='OT', max_length=2)),
                ('address', models.CharField(blank=True, max_length=75, null=True)),
                ('location', models.CharField(max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('format', models.CharField(choices=[('IP', 'IN_PERSON'), ('ON', 'ONLINE'), ('HB', 'HYBRID')], max_length=2)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('pix_key', models.CharField(blank=True, default='', max_length=77)),
                ('pix_key_owner', models.CharField(blank=True, default='', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', max_length=25)),
                ('pdf_link', models.URLField(blank=True, null=True, unique=True)),
                ('questionary_link', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=50)),
                ('phrase', models.CharField(max_length=100)),
                ('grade', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5')])),
                ('event_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event')),
            ],
        ),
    ]
