# Generated by Django 5.0.6 on 2024-05-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
