# Generated by Django 5.0.6 on 2024-05-22 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='project_FK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_app.project'),
        ),
    ]
