# Generated by Django 5.0.6 on 2024-05-25 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0002_event_profile_picture_event_project_fk'),
        ('project_app', '0002_rename_desctiption_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='profile_picture',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='project_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.project'),
        ),
    ]
