# Generated by Django 5.0.6 on 2024-05-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0003_alter_event_profile_picture_alter_event_project_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('IP', 'In person'), ('ON', 'Online'), ('HB', 'Hybrid')], max_length=2),
        ),
    ]
