# Generated by Django 5.0.6 on 2024-05-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0002_alter_community_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
