# Generated by Django 3.2.25 on 2024-06-06 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
