# Generated by Django 5.0.6 on 2024-05-24 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subcategory_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['title']},
        ),
    ]
