# Generated by Django 5.0.6 on 2024-05-19 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('COMMUNITY', 'Comunidade'), ('TOURIST SPOT', 'Ponto Turístico')], default='COMMUNITY', max_length=100)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('community_key', models.ForeignKey(limit_choices_to={'category': 'COMMUNITY'}, on_delete=django.db.models.deletion.CASCADE, to='community_app.community')),
            ],
        ),
    ]
